### ISSUE TITLE
Light switch on when touching the color slider

### ISSUE THREAD

**Issue by WesRos** [athombv/com.milight#10]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
In the Homey app, on a Apple and a Android device, a Mi Light switch on when you touch the color slider.

**What was the result?**
The bulb symbol status isn't switch to the "On" mode. (Bulb isn't bold)
When touching on the Bulb symbol, the symbol switch to the "On" mode. The light stays on.

**What did you expect as result?**
When touching the color slider, the light did not switch on.
Or when touching the color slider , switch light on after a delay. (longer time touching) And change the Bulb symbol to the "On" modes.

**Comment by RobinBol** [comment]
This should be fixed in v3.1.4 of the Milight app.
