### ISSUE TITLE
Milight app crashes or milight bridge is not responding.

### ISSUE THREAD

**Issue by 2benl** [athombv/com.milight#5]
A few minutes after installing a group of lights the milight bridge is not responding any more.
After a while the whole milight app crashes. When I reinstall or dis- and enable the app the ligth will work for a few minutes before it stops.

**Comment by 2benl** [comment]
This problem keeps persisting. I ordered the new iBox1 controller. Lot's of new Milight products including the possibility to set the saturation and color temperature. 
See: http://futlight.com/productlist.aspx?typeid=100

Will this new controller be supported?

**Comment by RobinBol** [comment]
Could you paste the stack strace with which the app crashes?

With regard to the iBox, not anytime soon, unless someone from the community is willing to create it.

**Comment by 2benl** [comment]
Sorry lost track of this issue. I installed a new usb power plug to the controller. First it was powered by an usb slot on my router. Now it is also further away from the router and all problema are gone. 

Too bad the iBox will not be supported soon. I would love to use the new light bulbs.
