### ISSUE TITLE
Missing Nightmode

### ISSUE THREAD

**Issue by Radiotechniman** [athombv/com.milight#6]
Not sure where to add this, git seemed a good option.. 
I'm missing the option of putting the MiLight's into Nightmode 

http://www.limitlessled.com/dev/

Thanks

**Comment by RobinBol** [comment]
Are you using the old bridge? With what bulbs?

**Comment by 2benl** [comment]
The option for nightmode is introduced with the iBox I think. So this may be part of issue #7

**Comment by RobinBol** [comment]
Night mode was already present in the older milight wifi box. Will be included in the coming major update (including iBox support).

**Comment by 2benl** [comment]
Looking forward to the major update. Love it that night mode will be included.

**Comment by RobinBol** [comment]
This is fixed in the mean time. Thanks for reporting!
