### ISSUE TITLE
Warm white color Swype in the Android App

### ISSUE THREAD

**Issue by WesRos** [athombv/com.milight#8]
When I'm swype the RGBW bulb to the warmest color in white. The App jump back to the coldest color. The same is happening in opposite direction.
Is this a issue in the Milight app, or the Android App? I don't have other devices with the same swype interface, so i couldn't test it.

I'm using Homey version 1.0.3 and Android app version: 2.3.0. Milight app version: 3.0.3

**Comment by RobinBol** [comment]
If you mean that you are using the mobile card in the Homey app for Android to adjust the temperature of the light, then this behavior is desired. It doesn't jump back to the coldest value, but to exactly .5. The RGBW bulb doesn't support different light temperatures, just a white color mode as far as I know.

**Comment by WesRos** [comment]
Yes, that what I meant. Thank you for your Feedback, so I could learn to better describe an issue.
I wasn't known that the Mi-Light couldn't switch the temperature in the White Color. The interface of the app predicted this function.
So this issue can be closed.
