### ISSUE TITLE
Milight toggels between on and offline

### ISSUE THREAD

**Issue by chrisesi** [athombv/com.milight#9]
When i try to add New milight bulbs or ledstrips to homey, hè can find them, but when i try to  turn them on or off they don't respond. I have one rgbw ledstrip that responds like it should and allso one RGB bulb. Allso verry often all the zones toggels between on and off. In total there are about 8 zones (14 bulbs and 5 ledstrips) that has to be controlled. I use an old wifi controler. The distance between homey and the controller is only 4 meter. After resetting homey i disabeled and wait 30 sec. Before i turned on the app again, nothing changed. In ther earlier versions of the homey software it worked like a charm. Could you look at it? Thx

**Comment by RobinBol** [comment]
Could you try if this still happens with the most recent version of the Milight App? If this is the case you can re-open this issue, but I expect it to be fixed already.
